# Default values for sck-otel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# Splunk Data-to-Everything Platform configuration.
# Fields `endpoint` and `token` are required to collect and send logs to Splunk Cloud or Splunk Enterprise.
splunkPlatform:
  # URL to a Splunk instance to send data to. ie) "http://X.X.X.X:8088/services/collector"
  endpoint: https://0.0.0.0:8088/services/collector
  # Splunk HTTP Event Collector token.
  token: "00000000-0000-0000-0000-000000000000"
  # Optional. Name of the Splunk index targeted.
  index:
  # Optional. Default value for `source` field.
  source:
  # Optional. Default value for `sourcetype` field. For container logs, it will be container name.
  sourcetype:
  # Maximum HTTP connections to use simultaneously when sending data. Defaults to 200.
  max_connections: 200
  # Whether to disable gzip compression over HTTP. Defaults to true.
  disable_compression: true
  # HTTP timeout when sending data. Defaults to 10s.
  timeout: 10s
  # Whether to skip checking the certificate of the HEC endpoint when sending data over HTTPS. Defaults to true.
  insecure_skip_verify: false
  # The PEM-format CA certificate for this client.
  # NOTE: The content of the certificate itself should be used here, not the file path.
  #       The certificate will be stored as a secret in kubernetes.
  clientCert:
  # The private key for this client.
  # NOTE: The content of the key itself should be used here, not the file path.
  #       The key will be stored as a secret in kubernetes.
  clientKey:
  # The PEM-format CA certificate file.
  # NOTE: The content of the file itself should be used here, not the file path.
  #       The file will be stored as a secret in kubernetes.
  caFile:

# Configurations for container logs
containerLogs:
  enabled: true
  # Container runtime. One of `docker`, `cri-o`, or `containerd`
  # Automatically discovered if not set.
  containerRuntime: "containerd"
