exporters:
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 2000
  splunk_hec:
    disable_compression: false
    endpoint: 
    index: main
    insecure_skip_verify: true
    max_connections: 2000
    source: otel
    sourcetype: k8s
    timeout: 10s
    token: 
extensions:
  health_check: {}
processors:
  batch: {}
  k8s_tagger:
    auth_type: kubeConfig
    extract:
      annotations:
      - key: splunk.com/index
      - key: splunk.com/sourcetype
      - key: splunk.com/exclude
      labels:
      - key: app
      metadata:
      - deployment
      - cluster
      - namespace
      - node
      - startTime
    filter:
      node_from_env_var: KUBE_NODE_NAME
    passthrough: false
    pod_association:
    - from: resource_attribute
      name: k8s.pod.uid
  memory_limiter:
    ballast_size_mib: 6553
    check_interval: 5s
    limit_mib: 13107
    spike_limit_mib: 4096
receivers:
  filelog:
    exclude:
    - /var/log/pods/default_rock-opentelemetry-collector*_*/opentelemetry-collector/*.log
    include:
    - /var/log/pods/*/*/*.log
    include_file_name: false
    include_file_path: true
    operators:
    - id: parser-docker
      output: extract_metadata_from_filepath
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: time
      type: json_parser
    - id: extract_metadata_from_filepath
      parse_from: $$attributes.file_path
      regex: ^\/var\/log\/pods\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[^\/]+)\/(?P<container_name>[^\._]+)\/(?P<run_id>\d+)\.log$
      type: regex_parser
    - resource:
        k8s.container.name: EXPR($.container_name)
        k8s.namespace.name: EXPR($.namespace)
        k8s.pod.name: EXPR($.pod_name)
        k8s.pod.uid: EXPR($.uid)
        run_id: EXPR($.run_id)
        stream: EXPR($.stream)
      type: metadata
    - id: clean-up-log-record
      ops:
      - move:
          from: log
          to: $
      type: restructure
    start_at: beginning
service:
  extensions:
  - health_check
  pipelines:
    logs:
      exporters:
      - splunk_hec
      processors:
      - batch
      - k8s_tagger
      receivers:
      - filelog
