{{- if or .Values.splunkPlatform.clientCert .Values.splunkPlatform.clientKey .Values.splunkPlatform.caFile -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "splunk-otel-collector.secret" . }}-certs
  labels:
    {{- include "splunk-otel-collector.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.splunkPlatform.clientCert }}
  hec_client_cert: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.splunkPlatform.clientKey }}
  hec_client_key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.splunkPlatform.caFile }}
  hec_ca_file: {{ . | b64enc }}
  {{- end }}
{{- end -}}