{{- if eq .Values.k8sMetadata.enabled true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}
  labels:
    {{- include "splunk-otel-collector.labels" . | nindent 4 }}
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "splunk-otel-collector.fullname" . }}]
- apiGroups:
    - ""
  resources:
    - "namespaces"
    - "pods"
  verbs:
    - "list"
    - "get"
    - "watch"
{{- end -}}
