{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splunk-otel-collector.fullname" . }}
  labels:
    {{- include "splunk-otel-collector.labels" . | nindent 4 }}
data:
  relay: |
    {{- include "splunk-otel-collector.agentCollectorConfig" . | nindent 4 -}}
{{- end }}
