{{ if and .Values.clusterDataCollector.enabled (eq (include "splunk-otel-collector.collectMetric" .) "true") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}-otel-k8s-cluster-receiver
  labels:
    app: {{ template "splunk-otel-collector.name" . }}
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  relay: |
    {{- $config := include "splunk-otel-collector.clusterDataCollectorConfig" . | fromYaml }}
    {{- .Values.clusterDataCollector.config | mustMergeOverwrite $config | toYaml | nindent 4 }}
{{- end }}
