{{ if and .Values.clusterDataCollector.enabled (eq (include "splunk-otel-collector.collectMetric" .) "true") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}-k8s-cluster-receiver
  labels:
    app: {{ template "splunk-otel-collector.name" . }}
    component: otel-k8s-cluster-receiver
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.clusterDataCollector.annotations }}
  annotations:
    {{- toYaml .Values.clusterDataCollector.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "splunk-otel-collector.name" . }}
      component: otel-k8s-cluster-receiver
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "splunk-otel-collector.name" . }}
        component: otel-k8s-cluster-receiver
        release: {{ .Release.Name }}
        {{- if .Values.clusterDataCollector.podLabels }}
        {{- toYaml .Values.clusterDataCollector.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-cluster-data-collector.yaml") . | sha256sum }}
        {{- if .Values.clusterDataCollector.podAnnotations }}
        {{- toYaml .Values.clusterDataCollector.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.autodetect.istio }}
        sidecar.istio.io/inject: "false"
        {{- end }}
    spec:
      serviceAccountName: {{ template "splunk-otel-collector.serviceAccountName" . }}
      {{- if .Values.clusterDataCollector.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.clusterDataCollector.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.clusterDataCollector.tolerations }}
      tolerations:
        {{ toYaml .Values.clusterDataCollector.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.clusterDataCollector.affinity }}
      affinity:
        {{- toYaml .Values.clusterDataCollector.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.clusterDataCollector.securityContext }}
      securityContext:
        {{ toYaml .Values.clusterDataCollector.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: otel-collector
        command:
        - /otelcol
        - --config=/conf/relay.yaml
        - --metrics-addr=0.0.0.0:8889
        {{- range .Values.clusterDataCollector.extraArgs }}
        - {{ . }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: SPLUNK_MEMORY_TOTAL_MIB
            value: "{{ include "splunk-otel-collector.convertMemToMib" .Values.clusterDataCollector.resources.limits.memory }}"
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: K8S_POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- if .Values.splunkObservability.accessToken }}
          - name: SPLUNK_O11Y_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "splunk-otel-collector.secret" . }}
                key: splunk_o11y_access_token
          {{- end }}
          {{- if .Values.splunkPlatform.token }}
          - name: SPLUNK_PLATFORM_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "splunk-otel-collector.secret" . }}
                key: splunk_platform_hec_token
          {{- end }}
          {{- with .Values.clusterDataCollector.extraEnvs }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
        readinessProbe:
          httpGet:
            path: /
            port: 13133
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        resources:
          {{- toYaml .Values.clusterDataCollector.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /conf
          name: collector-configmap
        {{- if .Values.clusterDataCollector.extraVolumeMounts }}
        {{- toYaml .Values.clusterDataCollector.extraVolumeMounts | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.clusterDataCollector.terminationGracePeriodSeconds }}
      volumes:
      - name: collector-configmap
        configMap:
          name: {{ template "splunk-otel-collector.fullname" . }}-otel-k8s-cluster-receiver
          items:
            - key: relay
              path: relay.yaml
      {{- if .Values.clusterDataCollector.extraVolumes }}
      {{- toYaml .Values.clusterDataCollector.extraVolumes | nindent 6 }}
      {{- end }}
      {{- if .Values.clusterDataCollector.priorityClassName }}
      priorityClassName: {{ .Values.clusterDataCollector.priorityClassName }}
      {{- end }}
{{- end }}
