{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "splunk-otel-collector.secret" . }}
  labels:
    {{- include "splunk-otel-collector.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.splunkPlatform.clientCert }}
  hec_client_cert: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.splunkPlatform.clientKey }}
  hec_client_key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.splunkPlatform.caFile }}
  hec_ca_file: {{ . | b64enc }}
  {{- end }}
  {{- if .Values.splunkObservability.accessToken }}
  splunk_o11y_access_token: {{ include "splunk-otel-collector.o11yAccessToken" . | b64enc }}
  {{- end }}
  {{- if .Values.splunkPlatform.token }}
  splunk_platform_hec_token: {{ include "splunk-otel-collector.platformHecToken" . | b64enc }}
  {{- end }}
{{- end -}}