{{ if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}
  labels:
    app: {{ template "splunk-otel-collector.name" . }}
    component: otel-collector
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.gateway.service.annotations }}
  annotations:
{{ toYaml . | trim | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
  {{- range $key, $port := .Values.gateway.ports }}
    {{- if $port.enabled }}
    - name: {{ $key }}
      containerPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
      {{- if $port.hostPort }}
      hostPort: {{ $port.hostPort }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector:
    app: {{ template "splunk-otel-collector.name" . }}
    component: otel-collector
    release: {{ .Release.Name }}
{{- end }}
