name: Release Charts

on:
  workflow_dispatch:
    name:
      description: 'Person to greet'
      required: true
      default: "rockb1017"
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v2.0.1
        env:
          CT_CHECK_VERSION_INCREMENT: "true"
        with:
          command: lint

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_repo_url: "https://github.com/splunk/sck-otel"
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
