name: Semgrep

on:
  pull_request: {}

jobs:
  semgrep:
    name: SAST Scan
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@v2

      - uses: returntocorp/semgrep-action@v1
        with:
          config: >- # more at semgrep.dev/explore
            p/security-audit
            p/secrets
            p/r2c-ci
            p/semgrep-rule-lints
        # Never fail the build due to findings on pushes.
        # Instead, just collect findings for semgrep.dev/manage/findings
          auditOff: push
